name: Modpack Release | Pipeline

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish Modpack to Github Releases
    runs-on: ubuntu-latest

    steps:
      # --- Checkout the repo
      - name: Check Out Git Repository
        uses: actions/checkout@v4

      # --- Install Packwiz
      - name: Install packwiz
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip"
          name: "packwiz"
          version: "linux"

      # --- Build Modrinth Pack
      - name: Build Modrinth Modpack
        run: |
          packwiz modrinth export -o mc101.mrpack
          echo "::notice ::⚙ Modpack has been exported as mc101.mrpack"
        shell: bash

      # --- Upload the pack to releases
      - name: Upload Modrinth Modpack to GitHub Releases
        run: |
          gh release upload $GITHUB_REF mc101.mrpack \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --clobber
          echo "::notice ::☀ Release $GITHUB_REF has been uploaded to Github Releases"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
